language: node_js

services:
  - "docker"

node_js:
  - "10"
  - "12"

cache:
  directories:
    - "node_modules"

after_success:
  - docker build -t aas-backend .

before_deploy:
  - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" docker.io ;
  - docker tag aas-backend $DOCKER_USERNAME/aas-backend:latest

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/aas-backend:latest ;

notifications:
  email: false
