language: node_js

services:
  - 'docker'

node_js:
  - '12'

cache:
  directories:
    - 'node_modules'

jobs:
  include:
    - stage: Build and deploy staging
      if: branch = develop
      before_deploy:
        - docker build -t sea-eu-around .
        - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" docker.io ;
        - docker tag sea-eu-around $DOCKER_USERNAME/sea-eu-around:staging
      deploy:
        provider: script
        script: docker push $DOCKER_USERNAME/sea-eu-around:staging;
        on:
          branch: develop

    - stage: Build and deploy prod
      if: branch = master
      before_deploy:
        - docker build -t sea-eu-around --build-arg NODE_ENV=prod .
        - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" docker.io ;
        - docker tag sea-eu-around $DOCKER_USERNAME/sea-eu-around:latest
      deploy:
        provider: script
        script: docker push $DOCKER_USERNAME/sea-eu-around:latest;
        on:
          branch: master

notifications:
  email: false
