language: node_js

services:
  - 'docker'

node_js:
  - '12'

cache:
  directories:
    - 'node_modules'

jobs:
  include:
    - stage: Test
      script: npm test
    - stage: Build and deploy staging
      if: branch = develop
      script: skip
      before_deploy:
        - docker build -t sea-eu-around .
        - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" docker.io ;
        - docker tag sea-eu-around $DOCKER_USERNAME/sea-eu-around:staging
      deploy:
        provider: script
        script: docker push $DOCKER_USERNAME/sea-eu-around:staging;
        on:
          branch: develop
      after_deploy:
        - "curl --location --request POST 'https://portainer.lad-dev.team/api/webhooks/0e4f6fcc-2c87-4076-977a-b0716e57984e'"

    - stage: Build and deploy prod
      if: branch = master
      script: skip
      before_deploy:
        - docker build -t sea-eu-around --build-arg NODE_ENV=prod .
        - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" docker.io ;
        - docker tag sea-eu-around $DOCKER_USERNAME/sea-eu-around:latest
      deploy:
        provider: script
        script: docker push $DOCKER_USERNAME/sea-eu-around:latest;
        on:
          branch: master
      after_deploy:
        - "curl --location --request POST 'https://portainer.lad-dev.team/api/webhooks/6a4dccc7-37ba-41c4-8f12-e17f2f2eaaa0'"

notifications:
  slack: adoptastudentgroupe:v2JQDHOZYPj2K0x01gjWMxuv
