api:
  dashboard: true

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'

providers:
  docker:
    network: proxy

certificatesResolvers:
  le:
    acme:
      email: sea-eu-around@univ-brest.fr
      storage: /certificates/acme.json
      tlschallenge: {}
