api:
  dashboard: true

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'

providers:
  docker:
    network: proxy

certificatesResolvers:
  letsencrypt:
    acme:
      email: sea-eu-around@univ-brest.fr
      storage: acme.json
      httpChallenge:
        entryPoint: http
