import { Column, Entity, OneToMany, OneToOne } from 'typeorm';

import { AbstractEntity } from '../common/abstract.entity';
import { LanguageType } from '../common/constants/language-type';
import { RoleType } from '../common/constants/role-type';
import { UserDto } from '../dto/UserDto';
import { MessageEntity } from './message.entity';
import { ProfileEntity } from './profile.entity';
import { UserRoomEntity } from './userRoom.entity';

@Entity({ name: 'user' })
export class UserEntity extends AbstractEntity<UserDto> {
    @Column({ type: 'enum', enum: RoleType, default: RoleType.USER })
    role: RoleType;

    @Column({ unique: true, nullable: true })
    email: string;

    @Column({ nullable: true })
    password: string;

    @OneToOne(() => ProfileEntity, (profile) => profile.user)
    profile: ProfileEntity;

    @Column({ nullable: false, default: false })
    isVerified: boolean;

    @Column({ nullable: false, default: false })
    onboarded: boolean;

    @Column({ nullable: true })
    locale?: LanguageType;

    @Column({ default: false, nullable: true })
    isAutoGenerated?: boolean;

    @OneToMany(() => MessageEntity, (message) => message.sender)
    messages: MessageEntity[];

    @OneToMany(() => UserRoomEntity, (userRoom) => userRoom.user)
    userRooms: UserRoomEntity[];

    // TODO: remove
    verificationToken?: string;

    dtoClass = UserDto;
}
