import { Column, Entity, OneToOne } from 'typeorm';

import { AbstractEntity } from '../common/abstract.entity';
import { LanguageType } from '../common/constants/language-type';
import { RoleType } from '../common/constants/role-type';
import { UserDto } from '../dto/UserDto';
import { ProfileEntity } from './profile.entity';

@Entity({ name: 'user' })
export class UserEntity extends AbstractEntity<UserDto> {
    @Column({ type: 'enum', enum: RoleType, default: RoleType.USER })
    role: RoleType;

    @Column({ unique: true, nullable: true })
    email: string;

    @Column({ nullable: true })
    password: string;

    @OneToOne(() => ProfileEntity, (profile) => profile.user, {
        cascade: true,
    })
    profile: ProfileEntity;

    @Column({ nullable: false, default: false })
    isVerified: boolean;

    @Column({ nullable: false, default: false })
    onboarded: boolean;

    @Column({ nullable: true })
    locale?: LanguageType;

    @Column({ default: false, nullable: true })
    isAutoGenerated?: boolean;

    @Column({ nullable: true })
    expoPushToken: string;

    // TODO: remove
    verificationToken?: string;

    dtoClass = UserDto;
}
