export enum StaffRoleType {
    TEACHING = 'TEACHING',
    RESEARCHER = 'RESEARCHER',
    SUPPORTING = 'SUPPORTING',
    ADMINISTRATIVE = 'ADMINISTRATIVE',
    TECHNICAL = 'TECHNICAL',
    AMBASSADOR = 'AMBASSADOR',
}
